### ISSUE TITLE
http.client error for python 2.7

### ISSUE THREAD

**Issue by yiboj** [lewismc/podaacpy#78] opened 2016-09-21 16:49 UTC
http.client is python 3.x, not compatible to earlier python

**Comment by lewismc** [comment] 2016-09-21 16:54
Thanks @yiboj I appreciate you writing here and telling us about it. Looks like we need to address this. Can you please post a trace or something which confirms the incompatibility? Our builds pass with Python 2.7, 3.3, 3.4 and there are no issues.

**Comment by yiboj** [comment] 2016-09-21 16:59
This is the traceback from test script:

Traceback (most recent call last):
  File "podaacpy_test.py", line 2, in <module>
    import podaac.podaac as podaac
  File "build/bdist.linux-x86_64/egg/podaac/podaac.py", line 19, in <module>
ImportError: No module named http.client

**Comment by Omkar20895** [comment] 2016-09-21 17:04
yes! There is a discrepancy here, I think I know why the build passed here, I did not write the test for the function  granule_subset, @lewismc I mentioned this earlier to you that I did not write the test since it sends a granule subset job request to the PO.DAAC server everytime, we forgot to address this later. My apologies for this. I will write a test for it. 

@yiboj is it okay if we send a duplicate job request to PO.DAAC for testing the function? I would like to send a request similar to [here](http://podaac.jpl.nasa.gov/ws/subset/granule/index.html).

**Comment by yiboj** [comment] 2016-09-21 17:06
ok
________________________________

**Comment by Omkar20895** [comment] 2016-09-21 17:40
@yiboj according to what I have observed, I tried to submit a empty json query like 

> {query : {}}

And still I am being returned a job token, isn't the json data being validated at the web service's side?? Thanks.

**Comment by yiboj** [comment] 2016-09-21 17:54
query should be validated by podaac web service, but I have to double check. Which service are you calling ?

**Comment by Omkar20895** [comment] 2016-09-21 18:24
Granule Subset.

**Comment by Omkar20895** [comment] 2016-09-25 17:04
@yiboj @lewismc the issue is solved but the discussion is still open on this thread. We can close this issue after we are done with the discussion. Thanks. :)

**Comment by lewismc** [comment] 2016-09-25 17:36
OK doke @Omkar20895 thanks. @yiboj would be excellent if you could let us know if there is some further validation required ion client side. For the time being I will push another release.

**Comment by yiboj** [comment] 2016-09-26 17:18
http.client works with python 2.7 now, thanks

**Closed** 2016-09-28 19:56 UTC
Labels: granule subset
